#!/bin/bash

PACKAGES=(
    numpy
    matplotlib
    scipy
    sympy
    ipython
    jupyter
    jupyterlab
    sjk
)

PYTHON=/usr/local/bin/python3
PIP=/usr/local/bin/pip3
PIPDIR=~/.personal_pip_dir
PIP_ARGS=()

while [[ $# -gt 0 ]]; do
    key="$1"
    case $key in
        -U|--upgrade|upgrade)
            PIP_ARGS+=("--upgrade")
            UPGRADE=yes
            shift
            ;;
        -a|--arg)
            [ "$2" ] && PIP_ARGS+=("$2")
            shift
            shift
            ;;
        *)
            shift
            ;;
    esac
done

if [ ! -x "$PYTHON" ]; then
    echo ERROR: python3 not found
    echo Please excute \`brew install python\'
    exit
fi

if [ ! -x "$PIP" ]; then
    echo ERROR: pip3 not found
    echo Please excute \`brew install python\'
    exit
fi

if [ -e "$PIPDIR" -a -z "$UPGRADE" ]; then
    echo WARNING: personal pip dir already exists
    echo If you want to resintall, please rename or delete \`~/.personal_pip_dir\'
    echo If you want to upgrade, please run \`brew pipsetup upgrade\'
    exit
fi

mkdir -p "$PIPDIR"

"$PIP" install --upgrade pip

PYTHONPATH="$PIPDIR/lib/python/site-packages"
export PYTHONPATH

for PACK in "${PACKAGES[@]}"; do
    "$PIP" install \
        --prefix="$PIPDIR" \
        "${PIP_ARGS[@]}" \
        "$PACK"
done

PYTHON_VER=`"$PYTHON" -c "import sys; print(sys.version[:3])"`

ln -f -s "/usr/local/bin/python3" "$PIPDIR/bin/python"
ln -f -s "/usr/local/bin/python3" "$PIPDIR/bin/python3"
ln -f -s "$PIPDIR/lib/python$PYTHON_VER" "$PIPDIR/lib/python"

for PIP_FILE in pip pip2 pip3; do
cat > "$PIPDIR/bin/$PIP_FILE" << 'EOF'
#!/bin/bash
echo No, you don\'t want to use pip directly.
echo Use: brew pip ...
echo To upgrade pip itself, use: brew pipsetup upgrade
EOF
chmod +x "$PIPDIR/bin/$PIP_FILE"
done
